# This file contains all common configurations that will be used in all environments
# Any environment-specific configuration must be defined in application-[environment].yml
server:
  port: 8080
grpc:
  port: 6565
management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]
  metrics:
    export:
      prometheus:
        enabled: true
mercury:
  url: "localhost"
  port: 8072
spring:
  application:
    name: sample-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample
    hikari:
      minimumIdle: 4
      idleTimeout: 600000
      maximumPoolSize: 8
      connectionTimeout: 30000
      maxLifetime: 1800000
  redis:
    timeout: 1000ms
  kafka:
    listener:
      concurrency: 4
    consumer:
      bootstrap-servers: localhost:9092
      group-id: default
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 30000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 30000
    producer:
      bootstrap-servers: localhost:9092
      acks: all
      buffer-memory: 33554432
      retries: 3
      batch-size: 200
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        retry.backoff.ms: 60000 # combine with `retries`
        linger.ms: 0 # combine with `batch-size`
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true