version: "3"
services:
  mars-service:
    image: nghiatn/mars-service:1.0
    ports:
      - "8080"
      - "8070"
    networks:
      - mars_network
      - cloud_native_network
    depends_on:
      - mysql-mars

  mysql-mars:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - mars_network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    volumes:
      - db-data:/var/lib/mysql
      - ./database/tshirtshop.sql:/docker-entrypoint-initdb.d/0_init.sql

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - jupiter_network
  kafka-cloud-native:
    image: wurstmeister/kafka
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka-jupiter
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
    networks:
      - cloud_native_network


networks:
  mars_network:
  cloud_native_network:
